services:
  - type: web
    name: chat-app-server
    env: node
    root: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: PORT
        value: 10000
      - key: ATLAS_URI_1
        sync: false
      - key: PROJECT_ID
        sync: false
      - key: REDIS_URL
        sync: false
